# theme: jekyll-theme-cayman
remote_theme: chailotl/cayman-dark
title: Chai's Portfolio
description: Hi, I'm Chai. I am a passionate programmer and aspiring game developer.
name: Chai
markdown: kramdown
